# Generated by Django 4.2.1 on 2023-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.DateTimeField()),
                ('power', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transmission_type', models.CharField(max_length=50)),
                ('body_style', models.CharField(max_length=50)),
                ('cylinder', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('engine_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
