# Generated by Django 4.2.1 on 2023-05-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_username_signup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='FN_usedCar_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='LN_usedCar_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='phone_usedCar_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='usedCar_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='usedCar_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='usedCar_nearestLocation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinder',
            field=models.IntegerField(blank=True, choices=[('4', '4'), ('6', '6'), ('8', '8')], null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(),
        ),
    ]
