# Generated by Django 4.2.1 on 2023-05-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FN_usedCar_user', models.CharField(blank=True, max_length=50, null=True)),
                ('LN_usedCar_user', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_usedCar_user', models.IntegerField(blank=True, null=True)),
                ('usedCar_city', models.CharField(blank=True, max_length=50, null=True)),
                ('usedCar_email', models.CharField(blank=True, max_length=50, null=True)),
                ('usedCar_nearestLocation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='FN_usedCar_user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='LN_usedCar_user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='phone_usedCar_user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='usedCar_city',
        ),
        migrations.RemoveField(
            model_name='car',
            name='usedCar_email',
        ),
        migrations.RemoveField(
            model_name='car',
            name='usedCar_nearestLocation',
        ),
        migrations.AddField(
            model_name='car',
            name='owner_car',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='car.personal_info'),
        ),
    ]
