# Generated by Django 4.2.1 on 2023-05-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_personal_info_remove_car_fn_usedcar_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.personal_info'),
        ),
    ]
