# Generated by Django 4.2.1 on 2023-05-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_car_owner_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FN_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('LN_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_owner', models.IntegerField(blank=True, null=True)),
                ('usedCar_city', models.CharField(blank=True, max_length=50, null=True)),
                ('email_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('nearestLocation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_car',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='car.owner'),
        ),
        migrations.DeleteModel(
            name='personal_info',
        ),
    ]
