# Generated by Django 4.2.1 on 2023-05-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_owner_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner_car',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='car.owner'),
        ),
    ]
